version: '3.6'
services:
  selenium-hub:
    image: selenium/hub:4.8.2-20230325
    container_name: selenium-hub
    restart: always
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      - SE_NODE_SESSION_TIMEOUT=60

  chrome1:
    image: selenium/node-chrome
    restart: always
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_DRAIN_AFTER_SESSION_COUNT=5
      - SE_NODE_SESSION_TIMEOUT=60

  chrome2:
    image: selenium/node-chrome
    restart: always
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_DRAIN_AFTER_SESSION_COUNT=5
      - SE_NODE_SESSION_TIMEOUT=60


  rabbitmq:
    image: rabbitmq:3.11.10-management-alpine
    container_name: 'rabbitmq'
    restart: always
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rb_data:/var/lib/rabbitmq/
        - rb_data:/var/log/rabbitmq

  orderservicebot:
    image: khangzxrr/order_service_bot:latest
    restart: always
    depends_on:
      - rabbitmq
      - selenium-hub
      - chrome1
      - chrome2

  order_service_web:
    image: khangzxrr/order_service_web:latest
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - rabbitmq
      - selenium-hub
      - orderservicebot
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Data Source=aspcore-staging.database.windows.net;Initial Catalog=order_service;Persist Security Info=True;User ID=aspnetapp-vnk;Password=@Khang2106@

volumes:
  rb_data: